name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: setup-java
      # Java 8 by default, doesn't really matter for us
      uses: olafurpg/setup-scala@v6

    - name: Gradle Build
      run: /bin/sh ./gradlew build

    - name: Gradle Publish
      run: /bin/sh ./gradlew -Pgpr.user=${{ github.actor }} -Pgpr.key=${{ secrets.GITHUB_TOKEN }} publish 
